### ISSUE TITLE
Grafana Dashboard

### ISSUE THREAD

**Issue by jakesie1309** [suprememoocow/victron-exporter#1]
Hi dude

Not really an issue, but more of a request :-). Love the dashboard you build in Grafana. Can share your json if possible. 

I am using Influx and Grafana and busy building this out. But looking at some ideas to speed up the process..

Thanx

**Comment by suprememoocow** [comment]
Hi @jakesie1309, I've exported it to https://gist.github.com/suprememoocow/fb1ac77af638a98cbf7224112c5a6e11 

Sorry for the delay in getting back to you!

**Comment by jakesie1309** [comment]
Hi Dude

 

No worries. Thank you so much.

 

Hope you guys are keeping safe in Cape Town. The weather here in Centurion is getting crazy. 
We have a heat wave.

 

Keep safe

Jakes
