### ISSUE TITLE
Username/Password as ENV var

### ISSUE THREAD

**Issue by FinweVI** [suprememoocow/victron-exporter#3]
Hey,

as far as I can tell, we can't pass ENV var to the exporter.

It could be helpful especially for the username and password options as we usually don't want to use them as CLI args or they'll end up visible by anyone on the system just looking at the running processes.

I can provide an MR with that if you're interested.

**Comment by suprememoocow** [comment]
Thanks @FinweVI, this makes a lot of sense. You're welcome to send an MR to do this. I think it should be fairly easy to do it from `main.go`.

**Comment by suprememoocow** [comment]
Closed in https://github.com/suprememoocow/victron-exporter/pull/11
